# Generated by Django 3.2.3 on 2021-05-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('age_limit', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=20)),
                ('application_fees', models.CharField(max_length=20)),
                ('start_date_to_apply', models.CharField(max_length=20)),
                ('end_date_to_apply', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=500)),
                ('how_to_apply', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('hiring_process', models.CharField(max_length=500)),
                ('is_goverment_job', models.BooleanField()),
            ],
        ),
    ]
