# Generated by Django 3.2.3 on 2021-05-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmodel', '0002_job_unique_url_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='job',
            name='age_limit',
        ),
        migrations.RemoveField(
            model_name='job',
            name='application_fees',
        ),
        migrations.AddField(
            model_name='job',
            name='age_relaxation',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='eligibility',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='exam_date',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='general_application_fees',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='how_to_pay_fees',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='last_date_to_fee_payment',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='maximum_age',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='minimum_age',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='ph_application_fees',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='sc_st_application_fees',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date_to_apply',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date_to_apply',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='unique_url_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
