# Generated by Django 3.2.3 on 2021-07-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmodel', '0004_auto_20210606_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSourceWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
    ]
