# Generated by Django 3.2.3 on 2021-07-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmodel', '0005_jobsourcewebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='notification_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
