# Generated by Django 3.2.3 on 2021-07-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmodel', '0006_job_notification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
