# Generated by Django 3.2.3 on 2021-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmodel', '0008_job_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
    ]
