# Generated by Django 3.2.3 on 2021-07-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmodel', '0009_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_form_url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
