# Generated by Django 3.2.3 on 2021-07-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmodel', '0010_job_application_form_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='job',
            name='general_application_fees',
        ),
        migrations.RemoveField(
            model_name='job',
            name='hiring_process',
        ),
        migrations.RemoveField(
            model_name='job',
            name='how_to_apply',
        ),
        migrations.RemoveField(
            model_name='job',
            name='how_to_pay_fees',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_goverment_job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='maximum_age',
        ),
        migrations.RemoveField(
            model_name='job',
            name='minimum_age',
        ),
        migrations.RemoveField(
            model_name='job',
            name='ph_application_fees',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='sc_st_application_fees',
        ),
        migrations.RemoveField(
            model_name='job',
            name='state',
        ),
        migrations.RemoveField(
            model_name='job',
            name='url',
        ),
        migrations.AddField(
            model_name='job',
            name='age',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AddField(
            model_name='job',
            name='application_fees',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='age_relaxation',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='eligibility',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
