# Generated by Django 3.2.3 on 2021-07-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobmodel', '0011_auto_20210705_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='age_relaxation',
        ),
        migrations.RemoveField(
            model_name='job',
            name='eligibility',
        ),
    ]
